<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYfEzzEZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYfEzzEZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYfEzzEZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYfEzzEZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYfEzzEZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YfEzzEZ',
    'container.build_id' => '1e858091',
    'container.build_time' => 1522862235,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYfEzzEZ');
